version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4.2
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:14
    working_dir: /home/Renan/Desktop/Estudos/Dockerfiles/clean-node-api
    restart: always
    command: bash -c "yarn install --production && yarn debug"
    volumes:
      - ./dist/:/home/Renan/Desktop/Estudos/Dockerfiles/clean-node-api/dist/
      - ./package.json:/home/Renan/Desktop/Estudos/Dockerfiles/clean-node-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo